### ISSUE TITLE
Can't install the plugin using cordova plugin add

### ISSUE THREAD

**Issue by paprikka** [contentment/AndroidInAppBilling#2]
### Steps to repro

1. create a new cordova project
2. add both ios and android platforms
3. run `cordova plugin install cordova plugin add https://github.com/contentment/AndroidInAppBilling.git --variable BILLING_KEY=WHATEVER`

### Logs
```
cordova plugin add https://github.com/contentment/AndroidInAppBilling.git --variable BILLING_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm3Qd60Zz54n8eLN5JUB8L6fvs5TxXmvX+GIPRIQbIJ2VumEL4KownJdGCvBNmjs4Q/lLShp9vHf8MKU5rk49Wifh6d5hJd+bU4olJIxUUOQR/7q7LT6IFR18Q9D2xbSdhdNUUs4iPd8ZsK3BmJHzfsSucHWmmOxYusnZz7/Ef7aL9Pdd/gury0KDvzPw1WxCtMBmapjIXBcU/VqwWuIIafVMltAJZ+fMvkHnfReeoUj+ubLtTd24/721NavviivnKMpCKcMec1CZ38A8z5drV29cr3ULxx4j8Aqxh7+gg8apWi+XeMo/MvU/YrzM/DrBAhECyGuh8TgYI7g8iROngQIDAQAB
Fetching plugin "https://github.com/contentment/AndroidInAppBilling.git" via git clone
Installing "com.smartmobilesoftware.androidinappbilling" for android
Installing "com.smartmobilesoftware.androidinappbilling" for ios
Error during processing of action! Attempting to revert...
Failed to install 'com.smartmobilesoftware.androidinappbilling':Error: Uh oh!
"/Users/rafal/Developer/Geist/Geist/plugins/com.smartmobilesoftware.androidinappbilling/src/ios/TransactionObserver.m" not found!
    at Object.module.exports.common.copyFile (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
    at Object.module.exports.common.copyNewFile (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
    at installHelper (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:54:16)
    at Object.module.exports.source-file.install (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:106:13)
    at installWrapper (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:76:32)
    at Object.ActionStack.process (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:543:20)
    at /Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
"/Users/rafal/Developer/Geist/Geist/plugins/com.smartmobilesoftware.androidinappbilling/src/ios/TransactionObserver.m" not found!
    at Object.module.exports.common.copyFile (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
    at Object.module.exports.common.copyNewFile (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
    at installHelper (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:54:16)
    at Object.module.exports.source-file.install (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:106:13)
    at installWrapper (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:76:32)
    at Object.ActionStack.process (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
    at handleInstall (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:543:20)
    at /Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
    at _fulfilled (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/rafal/.nvm/v0.10.35/lib/node_modules/cordova/node_modules/q/q.js:816:30)
```

**Comment by Czajnikowski** [comment]
22d8b44bc625862f6d4a32d5b6cc91ef9bfe806d
